--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/thebigsmileXD/customui
branches:
- master
projects:
  customui:
    path: "library"
    type: library
    model: virion
  customuitest:
    path: "example"
    libs:
      - src: XenialDan/customui/customui
        version: "^0.0"
...
